name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-pip python3-setuptools python3 python3-virtualenv zip unzip openjdk-8-jdk ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev
        pip install --upgrade Cython virtualenv buildozer

    - name: Initialize buildozer
      run: |
        buildozer init || true
        sed -i 's/title = .*/title = cases/' buildozer.spec
        sed -i 's/package.name = .*/package.name = cases/' buildozer.spec
        sed -i 's/package.domain = .*/package.domain = org.example/' buildozer.spec
        sed -i 's/source.include_exts = .*/source.include_exts = py,db/' buildozer.spec
        sed -i 's/requirements = .*/requirements = python3,kivy/' buildozer.spec
        sed -i 's/android.api = .*/android.api = 30/' buildozer.spec
        sed -i 's/android.minapi = .*/android.minapi = 21/' buildozer.spec

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: cases-apk
        path: ./bin/*.apk
